POST http://localhost:3001/login/
Content-Type: application/json

{
  "email": "srinivas.rao@example.com",
  "password": "Srin@1234!"
}

###

POST http://localhost:3001/biz-login/
Content-Type: application/json

{
  "name" : "Neha Singh",
  "password" : "Neha@2024"
}

###

GET http://localhost:3001/locations/

###

GET http://localhost:3001/featured-technicians/

###

GET http://localhost:3001/appliances/